### ISSUE TITLE
Provide support for Azure AD Application authentication

### ISSUE THREAD

**Issue by tomkerkhove** [jsturtevant/azure-k8-metrics-adapter#10]
Provide support for Azure AD Application authentication so that people are not forced to use MSI.
In certain enterprises this is not used (yet) for various reasons where the generated name for the AD App not aligning with naming convention is one.

This could be similar to how [Promitor](https://promitor.io/configuration/#authentication-with-azure-monitor) handles this is not a must.

**Comment by jsturtevant** [comment]
This is currently possible by modifying the deployment files to take secrets or env for authentication.  The azure-sdk first [looks for ENV variables then falls back to AIM](https://github.com/Azure/azure-sdk-for-go#more-authentication-details).  

This needs improvement to the docs in the Readme.md to point out possible configurations.

**Comment by tomkerkhove** [comment]
Thanks for the update, might try to contribute if I find some time.
