### ISSUE TITLE
Provide support for multiple subscriptions

### ISSUE THREAD

**Issue by tomkerkhove** [jsturtevant/azure-k8-metrics-adapter#9]
Provide support for multiple subscriptions. This is important when the cluster is shared with multiple teams which have their own subscription, but share the cluster isolated into multiple namespaces.

Currently from what I've seen only the subscription from the AKS cluster is supported, is that correct?

**Comment by jsturtevant** [comment]
Yes. Currently, it picks up the subscription from [Azure instance metadata service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service)  but with by supporting an Environment variable instead of AIM with issue #2 it would work with different subs as long as they were under the same AD Tenant.  

Working with multiple subscriptions would need more work but should be doable.

**Comment by jsturtevant** [comment]
What would this look like for you?  I would think you not only need to specify the subscription to pull the metric from but you might also want to specify the Service Principle Id to use?  Or would there be one identity in the tenant that has access to each resource across the subs?

If we add a `subscriptionid` [label](https://github.com/jsturtevant/azure-k8-metrics-adapter/blob/master/samples/servicebus-queue/deploy/hpa.yaml#L17) (and if nessary SP id) to the HPA request then I think this would be a way to specify which sub to reach out to for the metric.

**Comment by tomkerkhove** [comment]
My initial idea was indeed to have `subscriptionId` as a label in the HPA definition as well.
However, if none was specified I think it would make sense to assume that the adapter should use the subscription id of the cluster itself or a "default subscription id" environment variable.

This is to avoid a lot of duplication in scenarios where a cluster is not shared across subscriptions and thus a lot over overhead.

In terms of Service Principles - We use the same service principle for all subscriptions because in reality it's the same identity accessing it but I don't have a strong opinion on this one.

**Comment by jsturtevant** [comment]
I was thinking along the same lines.  It now supports this scenario.
